version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8090:8090"
    volumes:
      - ./:/app
networks:
      default: 
        external: 
          name: go-confluent-network
volumes:
  data: